version: "3.8"
services:

  hub:
    container_name: hub
    image: selenium/hub
    networks:
      robottestsnw: { }
    ports:
      - "4444:4444"

#    environment:
#      GRID_MAX_SESSION: 16
#      GRID_BROWSER_TIMEOUT: 3000
#      GRID_TIMEOUT: 3000

  chrome:
    image: selenium/node-chrome
    container_name: web-automation_chrome
    networks:
      robottestsnw: { }
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
#      HUB_PORT_4444_TCP_ADDR: hub
#      HUB_PORT_4444_TCP_PORT: 4444
#      NODE_MAX_SESSION: 4
#      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
    links:
      - hub

  firefox:
    image: selenium/node-firefox
    shm_size: '1gb'
    container_name: web-automation_firefox
    networks:
      robottestsnw: { }
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
#      HUB_PORT_4444_TCP_ADDR: hub
#      HUB_PORT_4444_TCP_PORT: 4444
#      NODE_MAX_SESSION: 2
#      NODE_MAX_INSTANCES: 2
    volumes:
      - ./:/dev/shm
    ports:
      - "9002:5900"
    links:
      - hub

  robottests:
    container_name: selenium_tests
    command: /bin/sleep infinity
    networks:
      robottestsnw: { }
    depends_on:
      - chrome
      - firefox
      - hub
    build: tests_robotframework/.
    volumes:
    - ./reports:/scripts/tests/
volumes:
  reports:

networks:
  robottestsnw:
    driver: bridge


